# Generated by Django 5.1.5 on 2025-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
