# Generated by Django 5.1.5 on 2025-09-23 05:49

import product.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_products_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=product.utils.uploads.product_upload_image_path),
        ),
    ]
