# Generated by Django 5.1.5 on 2025-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated_by',
            field=models.CharField(default='admin-user', max_length=20),
            preserve_default=False,
        ),
    ]
