# Generated by Django 5.1.5 on 2025-12-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="stock",
            new_name="_stock",
        ),
    ]
