# Generated by Django 5.1.5 on 2025-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_stock_inventory__stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
