# Generated by Django 5.1.5 on 2025-12-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_inventory_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
