# Generated by Django 5.1.5 on 2025-12-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_deactivated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
