# Generated by Django 5.1.5 on 2026-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="_stock",
            field=models.PositiveIntegerField(db_column="stock", default=0),
        ),
    ]
