# Generated by Django 5.1.5 on 2026-09-21 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordergroup_options_alter_ordergroup_status'),
        ('payment', '0002_remove_payment_order_payment_order_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='new_payment', to='order.ordergroup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], max_length=10)),
                ('provider_transaction_id', models.CharField(max_length=12)),
                ('channel', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_failure_code', models.CharField(max_length=64)),
                ('verification_failure_reason', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('authorization_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='active_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payment.paymenttransaction'),
        ),
    ]
