# Generated by Django 5.1.5 on 2026-09-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordergroup_options_alter_ordergroup_status'),
        ('payment', '0003_remove_payment_email_remove_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='order.ordergroup'),
        ),
    ]
