# Generated by Django 5.1.5 on 2026-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='verification_failure_code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='verification_failure_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
