# Generated by Django 5.1.5 on 2026-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenttransaction_verification_failure_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='provider_transaction_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='verification_failure_code',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('INITIALIZATION_FAILED', 'Initialization Failed'), ('INCONSISTENT', 'Inconsistent')], default='PENDING', max_length=24),
        ),
    ]
