# Generated by Django 5.1.5 on 2026-09-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_paymenttransaction_provider_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('INITIALIZATION_FAILED', 'Initialization Failed'), ('INCONSISTENT', 'Inconsistent'), ('REVERSED', 'Reversed')], default='PENDING', max_length=24),
        ),
    ]
