# Generated by Django 5.1.5 on 2025-07-22 08:30

import shop.utils.uploads
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('code', models.CharField(blank=True, max_length=7, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to=shop.utils.uploads.shop_logo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
