# Generated by Django 5.1.5 on 2025-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
