# Generated by Django 5.1.5 on 2026-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
