# Generated by Django 5.1.5 on 2025-09-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_unique_staff_id_per_shop_alter_user_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff_id',
            new_name='staff_handle',
        ),
    ]
