# Generated by Django 5.1.5 on 2025-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_telephone',
            field=models.CharField(max_length=20),
        ),
    ]
