# Generated by Django 5.1.5 on 2025-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('DIGITAL', 'Digital Payment'), ('CASH', 'Cash')], default='CASH', max_length=20),
        ),
    ]
