# Generated by Django 5.1.5 on 2025-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
