# Generated by Django 5.1.5 on 2025-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordergroup_cancelled_at_alter_ordergroup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
