# Generated by Django 5.1.5 on 2025-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
