# Generated by Django 5.1.5 on 2025-07-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_is_picked_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
