# Generated by Django 5.1.5 on 2025-12-18 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_ordergroup_is_paid_order_is_paid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop_name",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordergroup",
            name="email",
            field=models.EmailField(default=" ", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordergroup",
            name="full_name",
            field=models.CharField(default=" ", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
