# Generated by Django 5.1.5 on 2025-12-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_order_shop_name_ordergroup_email_and_more"),
        ("product", "0007_inventory_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
            ),
        ),
    ]
