# Generated by Django 5.1.5 on 2026-03-28 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_orderitem_product_description_orderitem_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroup",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
