# Generated by Django 5.1.5 on 2026-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_ordergroup_delivery_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordergroup",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PARTIALLY_FULFILLED", "Partially Fulfilled"),
                    ("FULFILLED_WITH_CANCELLATIONS", "Fulfilled with Cancellations"),
                    ("FULFILLED", "Fulfilled"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
